language: go

env:
  global:
    - PKG_CONFIG_PATH=$HOME/gopath/src/github.com/Corundex/database_exporter/include
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/oracle/instantclient_12_1

script:
  - sudo mkdir -p /opt/oracle
  - sudo wget -P /opt/oracle http://library.case.edu/instantclient-basic-linux.x64-12.1.0.2.0.zip
  - sudo wget -P /opt/oracle http://library.case.edu/instantclient-sdk-linux.x64-12.1.0.2.0.zip
  - sudo wget -P /opt/oracle http://library.case.edu/instantclient-sqlplus-linux.x64-12.1.0.2.0.zip
  - sudo unzip /opt/oracle/instantclient-basic-linux.x64-12.1.0.2.0.zip -d /opt/oracle
  - sudo unzip /opt/oracle/instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /opt/oracle
  - sudo unzip /opt/oracle/instantclient-sqlplus-linux.x64-12.1.0.2.0.zip -d /opt/oracle
  - sudo ln -s /opt/oracle/instantclient_12_1/libclntsh.so.12.1 /opt/oracle/instantclient_12_1/libclntsh.so
  - sudo apt-get install libaio1
  - go get github.com/golang/glog
  - go get github.com/golang/protobuf/proto
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/prometheus/client_model/go
  - go get github.com/prometheus/common/model
  - go get gopkg.in/yaml.v2
  - go get github.com/prometheus/client_golang/prometheus/promhttp
  - go get github.com/prometheus/common/expfmt
  - go get github.com/prometheus/common/version
  - go get github.com/denisenkom/go-mssqldb
  - go get github.com/go-sql-driver/mysql
  - go get github.com/kshvakov/clickhouse
  - go get github.com/lib/pq
  - go get github.com/mattn/go-oci8
  - go get github.com/mattn/go-sqlite3
  - make style
  - make vet
  - make test
  - make build
  - make docker

deploy:
  provider: releases
  api_key:
    secure: "Y9nuEQjjVThBqyb1NCqjs38GspoI6KsnP+4Esr9c0ReK/7dBhBY5IyAcQvuKSShaBFMRhHRRxwafxJ7mUnBGizOjynt4ml3hoI0zes8nflH9VCNYjbg5O/otA2tX2XEq9o5sg3Nd2ylb1EXbLdfjR46M1vkAK3H8z3HxTOhtRWcFn0Oar21iKyXHtkgslSGx8X2lEEEJz7YkCXxSvH7nFqDOSLh51VSw3ztwPX+lYzKutuUV15O9A3kQpr1iBHMG70c1uHJ6K5kb6l8cS0Mxl3yrcOtznWR1TxK7Yie3uBBmTVjRvSdUQA9swocnvmD/q9JznUkWjXqd1/DYAtEROgv7G//Y8+toTqSz2Dg1INo5M8IKmpvUKfTGKztgvwMfRvOPObd3YQm72CZtTpbbFYoNNgpamXlxfV7tMYtEcuz8O9Ol/xNcFJcJ2wuQJo61TqfM21lKw91cUQZw0EVdC2S/03QemTqMKInN+mkdBkilIWY1amTEM5GD7RIvIzGwiDeh12ScmJdw5SYODzBF7eyUwh5dxavzluXNLRA7tliFSwrjdnqrMZoXwwTCPc/ErQNAqwJewUNPk5K6q+DkJtx2l9mhjBoulAdV2f1yAdNOfzojQfxeAPAyOlXKGqxvioXhovNahUL328W36hesdBglHu3Gv6X1mTtsc0Z9CEQ="
  file:
    - database_exporter
  skip_cleanup: true
  on:
    tags: false
