language: go

env:
  global:
    - PKG_CONFIG_PATH=$HOME/gopath/src/github.com/Corundex/database_exporter

script:
  - go get github.com/golang/glog
  - go get github.com/denisenkom/go-mssqldb
  - go get github.com/go-sql-driver/mysql
  - go get github.com/kshvakov/clickhouse
  - go get github.com/lib/pq
  - go get github.com/mattn/go-oci8
  - go get github.com/mattn/go-sqlite3
  - make style
  - make vet
  - make test
  - make build
