language: go

env:
  global:
    - PKG_CONFIG_PATH=$HOME/gopath/src/github.com/Corundex/database_exporter/include

script:
  - go get github.com/golang/glog
  - go get github.com/golang/protobuf/proto
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/prometheus/client_model/go
  - go get github.com/prometheus/common/model
  - go get gopkg.in/yaml.v2
  - go get github.com/prometheus/client_golang/prometheus/promhttp
  - go get github.com/prometheus/common/expfmt
  - go get github.com/prometheus/common/version
  - go get github.com/denisenkom/go-mssqldb
  - go get github.com/go-sql-driver/mysql
  - go get github.com/kshvakov/clickhouse
  - go get github.com/lib/pq
  - go get github.com/mattn/go-oci8
  - go get github.com/mattn/go-sqlite3
  - make style
  - make vet
  - make test
  - make build
