name: Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      release_name:
        description: "Release name"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.11"

      - name: Install dependencies
        run: |
          go get github.com/golang/glog
          go get github.com/golang/protobuf/proto
          go get github.com/prometheus/client_golang/prometheus
          go get github.com/prometheus/client_model/go
          go get github.com/prometheus/common/model
          go get gopkg.in/yaml.v2
          go get github.com/prometheus/client_golang/prometheus/promhttp
          go get github.com/prometheus/common/expfmt
          go get github.com/prometheus/common/version
          go get github.com/denisenkom/go-mssqldb
          go get github.com/go-sql-driver/mysql
          go get github.com/kshvakov/clickhouse
          go get github.com/lib/pq
          go get github.com/go-goracle/goracle
          go get github.com/mattn/go-sqlite3
          go get github.com/couchbase/go_n1ql

      - name: Build project
        run: go build -o database_exporter ./...

      - name: List files
        run: ls -al

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  release:
    runs-on: ubuntu-latest
    needs: build
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: List files
        run: ls -al

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release notes for version ${{ github.ref }}
          draft: true
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/myapp # Adjust the path as needed
          asset_name: myapp # Adjust the name as needed
          asset_content_type: application/octet-stream
